[build]
    command = "yarn build"
    publish = "out"

[[plugins]]
    package = "@netlify/plugin-nextjs"

[[redirects]]
    from = "/lists/*"
    to = "https://lists.dropfilter.app/lists/:splat"
    status = 200
    headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
    from = "/api/*"
    to = "https://domaincord.com/api/:splat"
    status = 200
    headers = {Access-Control-Allow-Origin = "*"}