[build]
    command = "yarn build"
    publish = ".next"

[[redirects]]
    from = "/lists/*"
    to = "https://lists.dropfilter.app/lists/:splat"
    status = 200
    headers = {Access-Control-Allow-Origin = "*"}